uploads = []
outputs = []

[[generated]]
id = "vaPK6OIm7g_1sLXyTmTXm"
uri = "file://artifacts/minha-causa-justa/src/assets/hero-pessoa.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mY61VupwevYtExN8N4567"
uri = "file://artifacts/minha-causa-justa/src/assets/celular-pessoa.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nhnLb4y0kjh9VMD5ykWjn"
uri = "file://artifacts/minha-causa-justa/src/assets/familia-pessoa.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yRttEhbJbU7wcSOIFxQjF"
uri = "file://artifacts/minha-causa-justa/src/assets/confianca-pessoa.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PaBScnmSA9h3jaKUCyRUG"
uri = "file://artifacts/minha-causa-justa/src/assets/advogado-hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_d-m4-TbIqSlEcqC7KPgA"
uri = "file://artifacts/minha-causa-justa/src/assets/advogada-perfil.png"
type = "image"
title = "generated_image"
